### ISSUE TITLE
Java Script Error when trying to start Game

### ISSUE THREAD

**Issue by MacCrower** [lVlyke/starfield-mod-loader#4]
I have the Gamepass Version of Starfield and installed the Mod Loader.

When trying to start I get am Java Script Errps as seen on the screenshot

![grafik](https://github.com/lVlyke/starfield-mod-loader/assets/149329657/4fb61f83-0f08-4aaa-9799-edc2fb6365b5)

**Comment by lVlyke** [comment]
It looks like this is being caused by the profile's Game executable path being a relative path instead of absolute, and because of this it is looking for Starfield.exe in the wrong folder. Making the Game executable path absolute should fix this.

Alternatively, you can download the [latest release](https://github.com/lVlyke/starfield-mod-loader/releases), which now supports relative paths by using the profile's Game base directory.
